<% 
setting_Session = False 
setting_MultiLang = False
setting_DictPath = "Dictionaries/"
setting_CustomDict = "custom.txt"
setting_CSS=""
setting_UILang = "EN"
setting_Langs = "English (International)"
setting_Grammar = True
setting_CaseSensitive = True
setting_AllCaps = True
setting_Web = True
setting_Numeric = True
setting_NewLine = False
setting_CentralDictionary = False
'settings_BannedWords=array("profanity","profanity")
'settings_customTextArray
%>